-- ==========================================================
-- CANVA PRO STORE - MIGRATED TO NEON POSTGRESQL
-- Supabase has been completely removed.
-- Tables 'canva_plans' and 'canva_activations' are automatically
-- initialized and managed by backend/db.js inside Neon DB.
-- ==========================================================
